export default {
  work: 'Fullstack Developer',
  workDelivery: 'Mobile Apps/ Web Site',
  french: 'French',
  english: 'English',
  german: 'German',
  residence: 'Residence',
  city: 'City',
  age: 'Age',
  france: 'France',
  discover: 'Discover my Amazing',
  world: 'digital world !',
  explore: 'EXPLORE NOW',
  yearsExperience: 'Years Experience',
  appProduction: 'Apps in production',
  projectFinish: 'Completed Projects',
  useTechnology: 'technologies used',
  myService: 'My services',
  contactMe: 'Contact me',
  devWebTitle: 'Website development',
  devWebContent: 'The creation of a website is essential to improve the visibility of its activities. We can develop a website with a CMS (WordPress, Shopify, Prestashop) or directly from scratch via a programming language.',
  devAppTitle: 'Mobile application development',
  devAppContent: 'Today, more than half of the traffic on the web is done via a mobile device (smartphone, tablet). The development of a mobile application for your company is therefore a service that has become essential.',
  refTitle: 'Search engine optimization (SEO)',
  refContent: 'Your website is developed with the objective of appearing in the first pages on search engines.',
  hostingTitle: 'Hosting',
  hostingContent: 'Your website, database, api are hosted on a server, robust, supporting the rise in load and located closer to your visitors. We can use dedicated servers (like OVH) or solutions directly in the cloud (AWS, GCP).',
  maintenanceTitle: 'Maintenance',
  maintenanceContent: 'A healthy website (or mobile application) is an updated website. For a better user experience and security, maintenance is mandatory.',
  storeTitle: 'Management of mobile application stores (App Store, Play Store)',
  storeContent: 'Application creation on the stores. Validation of applications on the stores. Configuration of the application\'s page. Optimization for the referencing of the application. (ASO). Management of data protection and privacy policies.',
  recommendationTitle1: 'Valentin l\'adulte',
  recommendationContent1: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  recommendationTitle2: 'Leo maltraiter',
  recommendationContent2: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  recommendations: 'Recommendations',
  appFromScratch: 'Creation of an application from scratch',
  download: 'downloads',
  languageUsed: 'Language used',
  with: 'with',
  for: 'for',
  featuresMobile: 'Mobile Features',
  payOnline: 'Online payment',
  interApp: 'Internationalization of the application',
  libraryUsed: 'Libraries used',
  jobFeature: 'Business features developed',
  participateCampaign: 'Participation in campaigns.',
  answerSurvey: 'Respond to surveys.',
  participationMission: 'Participation in ambassador missions.',
  profile: 'Connection, registration, editing of his profile.',
  unConnectAccess: 'Access to the application in offline mode.',
  linkRS: 'Linking social networks (Instagram, tiktok, twitch, facebook) on its profile.',
  billing: 'Edition of administrative data in several steps.',
  tunnelRegister: 'Multi-stage registration with social networking and internal moderation.',
  participateCampaignRs: 'Participation in campaigns following social networks, influencer compensation and administrative data.',
  bfanTitle: 'Implementation of React native on existing applications for bFan Sport !',
  bfanDesc: '70 applications on the stores (AS Monaco, Stade-Francais, Paris-FC...)',
  bfanDev: 'Developed features',
  intReact: 'Integration of React Native on existing mobile applications in production (Play Store, App Store).',
  dev2View: 'Development of 2 new views in React Native with bridges and native modules (Swift, Java Android).',
  updateAPP: 'Update of React Native on Android and iOS.',
  mapDynamic: 'Creation of an interactive map in JavaScript for the Grand Prix du Castelet 2019 in production available on the Play Store and the App Store.',
  improveAuto: 'Improvement and automation of the IOS application creation process (Ruby, Fastlane, AWS).',
  deployment: 'Deployment of applications on the stores.',
  store: 'Store',
  campaign: 'Campaign',
  presentation: 'Connected',
  unConnected: 'Not connected',
  myProfile: 'My profile',
};
