export default {
  work: 'Fullstack Developer',
  workDelivery: 'Mobile Apps/ Web Site',
  french: 'French',
  english: 'English',
  german: 'German',
  residence: 'Residence',
  city: 'City',
  age: 'Age',
  france: 'France',
  discover: 'Discover my Amazing',
  world: 'digital world !',
  explore: 'EXPLORE NOW',
  yearsExperience: 'Years Experience',
  appProduction: 'Apps in production',
  projectFinish: 'Completed Projects',
  useTechnology: 'technologies used',
  myService: 'My services',
  contactMe: 'Contact me',
  devWebTitle: 'Développement de site web',
  devWebContent: 'La création de site web est indispensable pour améliorer la visibilité de ses activités.',
  devAppTitle: 'Développement d\'application mobile',
  devAppContent: 'Aujourd’hui, plus de la moitié du traffic sur le web est réalisé via un périphérique mobile (smartphone, tablette). Le développement d’une application mobile pour votre entreprise est donc un service devenu incontournable.',
  refTitle: 'Référencement (SEO)',
  refContent: 'Votre site internet est développé avec pour objectif d’apparaître dans les premières pages sur les moteurs de recherche.',
  hostingTitle: 'Hébergement',
  hostingContent: 'Votre site internet est hébergé sur un serveur puissant, robuste, supportant la montée en charge et situé au plus proche de vos visiteurs.',
  maintenanceTitle: 'Maintenance',
  maintenanceContent: 'Un site internet en bonne santé est un site internet mis à jour. Les forfaits de maintenance proposés sont le fruits d’années d’expérience et des solutions apportées à mes clients afin de vous garantir un site internet performant et fiable.',
  recommendationTitle1: 'Valentin l\'adulte',
  recommendationContent1: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  recommendationTitle2: 'Leo maltraiter',
  recommendationContent2: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  recommendations: 'Recommendations',
  appFromScratch: 'Creation of an application from scratch (development - deployment)',
  download: 'downloads',
  languageUsed: 'Language used',
  with: 'with',
  featuresMobile: 'Mobile Features',
  payOnline: 'Online payment',
  interApp: 'Internationalization of the application',
  libraryUsed: 'Libraries used',
  jobFeature: 'Business features developed',
  participateCampaign: 'Participation in campaigns.',
  answerSurvey: 'Respond to surveys.',
  participationMission: 'Participation in ambassador missions.',
  profile: 'Connection, registration, editing of his profile.',
  unConnectAccess: 'Access to the application in offline mode.',
  linkRS: 'Linking social networks (Instagram, tiktok, twitch, facebook) on its profile.',
  billing: 'Edition of administrative data in several steps.',
  tunnelRegister: 'Multi-stage registration with social networking and internal moderation.',
  participateCampaignRs: 'Participation in campaigns following social networks, influencer compensation and administrative data.',
  bfanTitle: 'Implementation of React native on existing applications for bFan Sport',
  bfanDesc: '70 applications on the stores (AS Monaco, Stade-Francais, Paris-FC...)',
  bfanDev: 'Developed features',
  intReact: 'Integration of React Native on existing mobile applications in production (Play Store, App Store).',
  dev2View: 'Development of 2 new views in React Native with bridges and native modules (Swift, Java Android).',
  updateAPP: 'Update of React Native on Android and iOS.',
  mapDynamic: 'Creation of an interactive map in JavaScript for the Grand Prix du Castelet 2019 in production available on the Play Store and the App Store.',
  improveAuto: 'Improvement and automation of the IOS application creation process (Ruby, Fastlane, AWS).',
  deployment: 'Deployment of applications on the stores.',
  store: 'Store',
  campaign: 'Campaign',
  presentation: 'Connected',
  unConnected: 'Not connected',
  myProfile: 'My profile',
};
