export default {
  work: 'Fullstack Développeur',
  workDelivery: 'App Mobile / Site Web',
  french: 'Français',
  english: 'Anglais',
  german: 'Allemand',
  residence: 'Pays',
  city: 'Ville',
  age: 'Âge',
  france: 'France',
  discover: 'Découvrez mon incroyable',
  world: 'monde digital !',
  explore: 'EXPLOREZ MAINTENANT',
  yearsExperience: 'Années d\'experiences',
  appProduction: 'Apps en production',
  projectFinish: 'Projets terminés',
  useTechnology: 'technologies utilisées',
  myService: 'Mes services',
  contactMe: 'Contactez-moi',
  devWebTitle: 'Développement de site web',
  devWebContent: 'La création de site web est indispensable pour améliorer la visibilité de ses activités.',
  devAppTitle: 'Développement d\'application mobile',
  devAppContent: 'Aujourd’hui, plus de la moitié du traffic sur le web est réalisé via un périphérique mobile (smartphone, tablette). Le développement d’une application mobile pour votre entreprise est donc un service devenu incontournable.',
  refTitle: 'Référencement (SEO)',
  refContent: 'Votre site internet est développé avec pour objectif d’apparaître dans les premières pages sur les moteurs de recherche.',
  hostingTitle: 'Hébergement',
  hostingContent: 'Votre site internet est hébergé sur un serveur puissant, robuste, supportant la montée en charge et situé au plus proche de vos visiteurs.',
  maintenanceTitle: 'Maintenance',
  maintenanceContent: 'Un site internet en bonne santé est un site internet mis à jour. Les forfaits de maintenance proposés sont le fruits d’années d’expérience et des solutions apportées à mes clients afin de vous garantir un site internet performant et fiable.',
  recommendationTitle1: 'Valentin l\'adulte',
  recommendationContent1: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  recommendationTitle2: 'Leo maltraiter',
  recommendationContent2: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  recommendations: 'Recommandations',
};
